# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/vele/Desktop/Workspace/Project_FPGA/unicorn_jig/const/io.xdc

# IP: C:/Users/vele/Desktop/Workspace/Project_FPGA/unicorn_jig/ip/ila_user_leds/ila_user_leds.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_user_leds || ORIG_REF_NAME==ila_user_leds} -quiet] -quiet
